// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SeCsLkfzOLvviv8vuiF_NUNcrjpu5io',
    appId: '1:875998740711:web:17ed7f4325407eedc62242',
    messagingSenderId: '875998740711',
    projectId: 'chronic-illness-app-dd39a',
    authDomain: 'chronic-illness-app-dd39a.firebaseapp.com',
    storageBucket: 'chronic-illness-app-dd39a.firebasestorage.app',
    measurementId: 'G-Z3LB8TSZ6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGllZi24FlF7fr7P2Tog01Nk-la5tDrCo',
    appId: '1:875998740711:android:4ea84c9719603022c62242',
    messagingSenderId: '875998740711',
    projectId: 'chronic-illness-app-dd39a',
    storageBucket: 'chronic-illness-app-dd39a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmOT0IKEuPbndImiq2N5m-eZv53gShWWM',
    appId: '1:875998740711:ios:27a0ea1d25db5284c62242',
    messagingSenderId: '875998740711',
    projectId: 'chronic-illness-app-dd39a',
    storageBucket: 'chronic-illness-app-dd39a.firebasestorage.app',
    iosClientId: '875998740711-hg1pfl0kosa5p8nrebmtv93bma961gd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chronicIllnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmOT0IKEuPbndImiq2N5m-eZv53gShWWM',
    appId: '1:875998740711:ios:27a0ea1d25db5284c62242',
    messagingSenderId: '875998740711',
    projectId: 'chronic-illness-app-dd39a',
    storageBucket: 'chronic-illness-app-dd39a.firebasestorage.app',
    iosClientId: '875998740711-hg1pfl0kosa5p8nrebmtv93bma961gd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chronicIllnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2SeCsLkfzOLvviv8vuiF_NUNcrjpu5io',
    appId: '1:875998740711:web:8f60cf4e6c3dbda9c62242',
    messagingSenderId: '875998740711',
    projectId: 'chronic-illness-app-dd39a',
    authDomain: 'chronic-illness-app-dd39a.firebaseapp.com',
    storageBucket: 'chronic-illness-app-dd39a.firebasestorage.app',
    measurementId: 'G-M2RJ2127VW',
  );
}
